### ISSUE TITLE
His slogan each word on new line.

### ISSUE THREAD

**Issue by LagShaggy** [LagShaggy/kaanpeeters_site#16]
I create Music, Text and Moments
Ich creiere Musik, Text und Momente

These three nouns each on a new line.
Here you have a bit of freedom, just make them look better, such that they are more apparent and visible, such that it is immediately visible to the viewer.

**Comment by DJassassin4u** [comment]
Did, now to make each line show up in sequence.

**Comment by LagShaggy** [comment]
nice!
