### ISSUE TITLE
Check German translation for event texts

### ISSUE THREAD

**Issue by DJassassin4u** [LagShaggy/kaanpeeters_site#31]
So I have this for the English version:
	"events.text1": "Next Events",
	"events.text2": "View All Events",
	"events.text3": "Close All Events",
	"events.text4": "Also Show Past Events"
And this for German version:
	"events.text1": "Nächste Events",
	"events.text2": "Alle Veranstaltungen anzeigen",
	"events.text3": "Schließen Sie alle Ereignisse",
	"events.text4": "Zeigen Sie auch vergangene Ereignisse an"
But these seem long and weird. Can you give me some shorter ones or more appropriate ones?

**Comment by LagShaggy** [comment]
I have changed them.
